import { list } from './list/list';
import { data } from './data/data';
import { mapContainer } from './map/mapContainer';
import { createTable } from './table/table';
import { createGraphic } from './graphic/createGraphic';
import { createFooter } from './footer/footer';

data();
const WRAPPER = document.createElement('div');
WRAPPER.style.display = 'flex';
WRAPPER.style.flexWrap = 'wrap';
WRAPPER.style.maxWidth = '800px';
WRAPPER.style.margin = '0 auto';
const LM_WRAPPER = document.createElement('div');
LM_WRAPPER.style.display = 'flex';
LM_WRAPPER.style.flexWrap = 'wrap';
LM_WRAPPER.style.justifyContent = 'space-between';
LM_WRAPPER.style.width = '100%';
LM_WRAPPER.style.marginBottom = '5px';
LM_WRAPPER.append(list(), mapContainer());
WRAPPER.appendChild(LM_WRAPPER);
document.querySelector('body').appendChild(WRAPPER);
const LG_WRAPPER = document.createElement('div');
LG_WRAPPER.style.display = 'flex';
LG_WRAPPER.style.flexWrap = 'wrap';
LG_WRAPPER.style.justifyContent = 'space-between';
LG_WRAPPER.style.width = '100%';
WRAPPER.appendChild(LG_WRAPPER);
createTable(LG_WRAPPER);
createGraphic(LG_WRAPPER);
WRAPPER.appendChild(createFooter());
